name: Deploy V2 Docs and demos

on:
  push:
    tags:
      - v2.**

jobs:
  deploy-netlify-docs:
    name: Deploy V2 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run build

      - name: Docs build
        env:
          NETLIFY: true
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run docs:vite-build

      - name: Combine output
        run: |
          yarn cpx "docs/add-this/dist/**" dist/add-this
          yarn cpx "docs/blog2/dist/**" dist/blog
          yarn cpx "docs/comment2/dist/**" dist/comment
          yarn cpx "docs/components/dist/**" dist/components
          yarn cpx "docs/copy-code2/dist/**" dist/copy-code
          yarn cpx "docs/copyright2/dist/**" dist/copyright
          yarn cpx "docs/feed2/dist/**" dist/feed
          yarn cpx "docs/lightgallery/dist/**" dist/lightgallery
          yarn cpx "docs/md-enhance/dist/**" dist/md-enhance
          yarn cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          yarn cpx "docs/pwa2/dist/**" dist/pwa
          yarn cpx "docs/reading-time2/dist/**" dist/reading-time
          yarn cpx "docs/redirect2/dist/**" dist/redirect
          yarn cpx "docs/redirect2/dist/**" dist/redirect
          yarn cpx "docs/sass-palette/dist/**" dist/sass-palette
          yarn cpx "docs/seo2/dist/**" dist/seo
          yarn cpx "docs/sitemap2/dist/**" dist/sitemap
          yarn cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: netlify
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee-docs:
    name: Deploy V2 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run build

      - name: Docs build
        env:
          BASE: /v2/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run docs:vite-build

      - name: Combine output
        run: |
          yarn cpx "docs/add-this/dist/**" dist/add-this
          yarn cpx "docs/blog2/dist/**" dist/blog
          yarn cpx "docs/comment2/dist/**" dist/comment
          yarn cpx "docs/components/dist/**" dist/components
          yarn cpx "docs/copy-code2/dist/**" dist/copy-code
          yarn cpx "docs/copyright2/dist/**" dist/copyright
          yarn cpx "docs/feed2/dist/**" dist/feed
          yarn cpx "docs/lightgallery/dist/**" dist/lightgallery
          yarn cpx "docs/md-enhance/dist/**" dist/md-enhance
          yarn cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          yarn cpx "docs/pwa2/dist/**" dist/pwa
          yarn cpx "docs/reading-time2/dist/**" dist/reading-time
          yarn cpx "docs/redirect2/dist/**" dist/redirect
          yarn cpx "docs/sass-palette/dist/**" dist/sass-palette
          yarn cpx "docs/seo2/dist/**" dist/seo
          yarn cpx "docs/sitemap2/dist/**" dist/sitemap
          yarn cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-theme-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run build

      - name: Build Netlify Demo
        run: yarn workspace theme-demo demo:vite-build

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2-demo
          branch: netlify
          folder: demo/theme/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Gitee Demo
        env:
          BASE: /v2-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: yarn workspace theme-demo demo:vite-build

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2-demo
          branch: gitee
          folder: demo/theme/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-plugin-demo:
    name: Deploy ${{ matrix.plugin-name }} demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin-name:
          - add-this
          - blog2
          - comment2
          - copy-code2
          - copyright2
          - feed2
          - lightgallery
          - md-enhance
          - photo-swipe
          - pwa2
          - redirect2
          - sass-palette
          - seo2
          - sitemap2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run build

      - name: Build ${{ matrix.plugin-name }} demo
        env:
          BASE: /${{ matrix.plugin-name }}-demo/
          HOSTNAME: https://vuepress-theme-hope.github.io/
        run: yarn workspace ${{ matrix.plugin-name }}-demo demo:vite-build

      - name: Deploy ${{ matrix.plugin-name }} demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.plugin-name }}-demo
          branch: gh-pages
          folder: demo/${{ matrix.plugin-name }}/src/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
